### ISSUE TITLE
Question about my little problem

### ISSUE THREAD

**Issue by anes66** [Musiker15/gp_deathcounter#2]
So first of all thank you for sharing you work with us :) So my problem is when i kill for example myself in database it count 1 but ingame im waiting for a medic to revive me or i use /revive the counter is still on 1 death and thats not correct becouse a medic or a admin revived the player how can i make it to not count like that. I hope you understand what i mean.

So bassicly said when the death timer is on 0min and 0 sec and after respawn in hospital with losing all items then to count as a dead

**Comment by Musiker15** [comment]
Sorry, but that isn't possible.
